// 화면 문구 (D-086: 다국어를 넣을 때 이 파일을 언어별로 나눈다). 대사·나레이션 본문은 data/에 있다.
// 여기에는 버튼·안내·결과 요약 같은 기능 문구만 둔다.

export const T = {
  forecast: {
    title: '예상 승률',
    win: '승',
    loss: '패',
    low: '<1%',
    high: '>99%',
    percent: (n: number) => `${n}%`,
    none: '남은 국면으로는 승부가 나지 않는다',
  },

  title: '제6차 성배전쟁',
  subtitle: '후유키 · 7일',
  statsPending: '우승자 비율 · 준비 중',
  summonRandomTag: '랜덤 소환',
  summonCatalystTag: '촉매 소환',
  copyright: 'This is a non-profit fan project. All rights to "Fate" series and related assets belong to TYPE-MOON / FGO PROJECT.',
  fatePoints: '운명점',
  fatePointsHint: '판정을 다시 굴릴 수 있는 횟수. 게임 중에는 회복되지 않는다.',
  summonRandom: '소환',
  summonCatalyst: '촉매 소환',
  catalystTitle: '촉매를 고른다',
  catalystHint: '연이 닿은 영령이 응답한다.',
  catalystSearch: '이름 검색 (초성도 된다)',
  catalystAll: '전체',
  catalystCount: (n: number) => `${n}기`,
  catalystNone: '응답하는 영령이 없다.',
  catalystExtra: '난입',
  back: '돌아가기',
  summoning: '소환 중…',
  skipChant: '영창 생략 ▸▸',
  startWar: '성배전쟁 시작',
  loading: '불러오는 중…',
  noblePhantasm: '보구',
  alignment: { good: '선', neutral: '중립', evil: '악' } as Record<string, string>,
  stat: { str: '근력', end: '내구', agi: '민첩', mana: '마력', luck: '행운', np: '보구' } as Record<string, string>,
  condition: { full: '만전', hurt: '부상', danger: '위험' } as Record<string, string>,
  affinityTier: { hostile: '적대', wary: '경계', neutral: '중립', friendly: '호감', loyal: '충성' } as Record<string, string>,
  intelLevel: ['정보 없음', '클래스', '스테이터스', '진명'],
  time: { day: '낮', night: '밤', final: '강제 전투' } as Record<string, string>,
  dayN: (d: number) => `${d}일째`,
  mana: '마력',
  affinity: '호감도',
  seals: '영주',
  enemies: '적 진영',
  log: '기록',
  unknownMaster: '미확인 마스터',
  actions: {
    move: { icon: '👣', label: '이동' },
    intel: { icon: '🔍', label: '정보 수집' },
    bond: { icon: '🤝', label: '교류' },
    supply: { icon: '💧', label: '마력 공급' },
  },
  actionReason: { night: '밤에는 이동만 할 수 있다', supplied_today: '마력 공급은 하루 한 번', intel_complete: '모든 적의 진명을 안다' } as Record<string, string>,
  pickTile: '이동할 칸을 누른다. 지금 칸을 누르면 머문다. 밤을 마친 칸이 내일의 보너스가 된다',
  stay: '머무르기',
  role: { leyline: '영맥', intel: '정보', bond: '교류' } as Record<string, string>,
  // 낮에는 보너스 수치를 보이지 않고 확률이 오른다는 느낌만 준다 (D-156)
  roleBonus: { leyline: '아침 마력 공급 성공률 ↑', intel: '정보 수집 성공률 ↑', bond: '교류 성공률 ↑' } as Record<string, string>,
  roleHint: '밤을 마친 칸의 역할이 다음 날 보너스가 된다',
  // 낮 메뉴 (D-145)
  dayQ: (day: number, place: string, role: string, bonus: string) => `${day}일차 낮 · ${place} (${role}) — 오늘은 무엇을 할까? ${bonus}`,
  dayBonus: (what: string) => `칸 보너스: ${what}`,
  dayIntel: (bonus: boolean) => `🔍 정보 수집${bonus ? ' (성공률 ↑)' : ''}`,
  dayIntelWhy: '모든 적의 진명을 안다',
  dayBond: (who: string, bonus: boolean) => `🤝 ${who}와(과) 교류${bonus ? ' (성공률 ↑)' : ''}`,
  cmd: {
    q: (i: number) => `국면 ${i} — 지시를 내릴까?`,
    qCounter: '적이 보구를 개방하려 한다. 맞서서 보구를 개방할까?',
    np: (a: number, b: number) => `보구 개방 (마력 ${a} → ${b})`,
    npLow: (a: number, need: number) => `보구 개방 (마력 ${a}/${need})`,
    npLowWhy: (a: number, need: number) => `마력이 모자라다 (${a}/${need}). 영주로는 즉시 발동할 수 있다`,
    sealNp: (n: number) => `영주: 보구 즉시 발동 (남은 ${n}획)`,
    weakness: (phase: string) => `약점 공략 — ${phase}(으)로 끌고 간다 (전투당 1회)`,
    none: '지시하지 않는다',
    noneCounter: '맞서지 않는다',
  },
  supplyHurtQ: (who: string, cond: string) => `${who}이(가) 크게 다친 듯하다 (${cond}). 마력 공급으로 상태를 완화해 볼까?`,
  supplyTrustQ: (who: string) => `${who}이(가) 마스터를 깊게 신뢰하고 있는 듯하다. 마력 공급을 진행할까?`,
  supplyYes: '마력 공급을 한다',
  supplyNo: '오늘은 그만둔다',
  cancel: '취소',
  // 조우
  encounterTitle: '조우',
  encounterBody: (enemy: string, master: string, place: string) => `${place}. ${master}와(과) ${enemy}이(가) 모습을 드러냈다.`,
  ambushedByMe: '기습에 성공했다. 첫 국면의 주도권을 쥔다.',
  ambushedByThem: '기습당했다. 첫 국면의 주도권을 빼앗겼다.',
  fight: '전투 개시',
  flee: '도주',
  // 전투 개입
  phaseN: (i: number) => `국면 ${i}`,
  sealCommandQ: (n: number) => `영주를 사용할까? (남은 ${n}획)`,
  sealNp: '영주: 보구 즉시 발동',
  sealNone: '사용하지 않는다',
  npOpenQ: (mana: number) => `보구를 개방할까? (마력 ${mana})`,
  npCounterQ: '적이 보구를 개방하려 한다. 맞서서 보구를 개방할까?',
  sealCounterQ: (n: number) => `적이 보구를 개방하려 한다. 영주를 사용할까? (남은 ${n}획)`,
  npOpen: '보구 개방',
  npHold: '보류',
  rollCta: '주사위를 굴린다',
  battleOver: '전투 종료',
  fx: { guard: '버텨 냈다', fall: '▼ 전투 불능', skill: '스킬 발동', negate: '무효', weakness: '약점 공략', comeback: '역전', comebackSub: '끝까지 서 있었다' },
  sealBurst: '영주로 명한다',
  sealBurstEnemy: (m: string) => `${m || '상대 마스터'}이(가) 영주를 사용했다`,
  sealsLeft: (n: number) => `남은 영주 ${n}획`,
  masterLabel: '마스터',
  masterMe: '나 (플레이어)',
  temperament: { aggressive: '호전', proud: '오만', cautious: '신중', cunning: '교활' } as Record<string, string>,
  threshold: '목표값 (이상이면 성공)',
  success: '성공',
  failure: '실패',
  chase: '추격',
  opponent: '상대',
  rollTitle: '판정',
  stayHere: '이 칸에 머문다 (행동 1회 소비)',
  verdict: {
    tie: '동점 · 국면 스킵',
    fateOk: '행운 판정 성공 · 국면 스킵',
    defended: (who: string) => `${who} 버텨 냄 · 피해 없음`,
    fateFail: (who: string) => `${who} 행운 판정 실패 · 1단계 하락`,
    win: (who: string, margin: number, drop: number) => `${who} 승 · 차이 ${margin} · ${drop}단계 하락`,
  },
  rerollQ: (n: number) => `운명점으로 다시 굴릴까? (남은 ${n})`,
  reroll: '다시 굴린다',
  keep: '이대로 간다',
  dangerQ: (who: string) => `${who}이(가) 위험하다. 한 번 더 맞으면 쓰러진다. 어떻게 할까?`,
  dangerFight: '계속 싸운다 (한 번 더 맞으면 패배)',
  escapeSeal: (n: number) => `영주로 퇴각 (확정 성공, 남은 ${n}획)`,
  escapeRun: '일반 도주 (민첩 대항, 실패하면 패배)',
  postTitle: '패배한 마스터',
  postQ: (master: string) => `${master}을(를) 어떻게 할까?`,
  execute: '처치',
  release: '방면',
  betrayalTitle: '배신',
  betrayalQ: (n: number) => `서번트가 등을 돌렸다. 영주로 막을까? (남은 ${n}획)`,
  betrayalBlock: '영주로 저지',
  betrayalAccept: '막지 않는다',
  // 판정 표시
  dice: '주사위',
  miracle: '기적',
  total: '판정값',
  hiddenStats: '미공개 스테이터스',
  dc: (n: number) => `목표 ${n}`,
  vs: 'VS',
  part: { affinity: '호감도', intel: '정보', role: '칸 보너스', leyline: '영맥', ambush: '기습', skill: '스킬', foeSkill: '상대 스킬', presence_detection: '기척감지', cap: '보정 상한', modifier: '보정' } as Record<string, string>,
  // 결과 요약 (시스템 문구)
  sys: {
    intelOk: (who: string, what: string) => `정보 수집 성공 — ${who}의 ${what}을(를) 알아냈다.`,
    intelFail: '정보 수집 실패 — 단서를 놓쳤다.',
    npReveal: (name: string) => `보구 개방으로 진명이 드러났다: ${name}`,
    supply: (result: string, a: number, b: number) => `마력 공급 ${result} — 마력 ${a} → ${b}`,
    supplyResult: { great: '대성공', success: '성공', normal: '보통', fail: '실패', fumble: '대실패' } as Record<string, string>,
    bond: (ok: boolean) => (ok ? '교류 성공' : '교류 실패'),
    intelMet: (who: string) => `조우 — 상대의 클래스를 확인했다: ${who}`,
    intelBattle: (who: string, what: string) => `칼을 맞댄 끝에 ${who}의 ${what}을(를) 알아냈다.`,
    weakness: (who: string, phase: string) => `약점 공략 — ${who}의 약점을 찔러 ${phase}(으)로 끌고 간다.`,    affinity: (a: number, b: number, tier: string) => `호감도 ${a} → ${b} (${tier})`,
    refused: '서번트가 명령을 거부했다.',
    escapeOk: '도주에 성공했다.',
    escapeFail: '도주에 실패했다.',
    enemyEscaped: '상대가 물러났다.',
    enemyEscapeFail: '상대가 도주하려 했지만 놓치지 않았다.',
    parted: '서로 싸우지 않고 물러났다.',
    seal: (purpose: string, n: number) => `영주 사용: ${purpose} (남은 ${n}획)`,
    sealPurpose: { np: '보구 즉시 발동', escape: '도주', block_betrayal: '배신 저지' } as Record<string, string>,
    battleEnd: { win: '승리', loss: '패배', draw: '무승부', escape: '도주' } as Record<string, string>,
    recovered: (a: string, b: string) => `하룻밤이 지나 상태가 회복되었다 (${a} → ${b}).`,
    betrayal: '서번트가 배신하려 한다.',
    betrayalBlocked: '영주의 구속으로 배신을 막았다.',
    finalStart: (n: number) => `일곱째 밤이 끝났다. 남은 ${n}진영이 중앙 공원으로 불려 나온다.`,
    bracket: (r: number, pairs: string, bye: string | null) => `라운드 ${r} — ${pairs}${bye ? ` / 부전승: ${bye}` : ''}`,
    eliminatedEnemy: (who: string) => `${who}이(가) 전쟁에서 탈락했다.`,
    playerOut: '당신의 성배전쟁은 여기서 끝났다.',
    check: (total: number, dc: number | null) => (dc === null ? `(판정 ${total})` : `(판정 ${total} / 목표 ${dc})`),
    // 스킬 자동 발동 (D-142): 판정 보정 외의 효과만 글로 알린다. 판정 보정은 판정 카드와 연출이 보인다
    skillGuard: (skill: string) => `${skill} — 쓰러지지 않고 위험에서 버틴다.`,
    skillMana: (skill: string, who: string, a: number, b: number) => `${skill} — ${who}의 마력 ${a} → ${b}`,
    battleStart: (place: string) => `전투 개시${place ? ` — ${place}` : ''}`,
    enemyNp: (who: string) => `${who}이(가) 보구를 개방했다!`,
    sealNp: '영주의 명령으로 보구를 즉시 발동했다.',
    myNp: (a: number, b: number) => `보구 개방 — 마력 ${a} → ${b}`,
    damage: (who: string, drop: number, from: string, to: string | null) =>
      to ? `${who} 패배: ${drop === 2 ? '큰 피해를 입었다' : '피해를 입었다'}. ${from} → ${to}` : `${who} 패배: 더는 버틸 수 없다. ${from} → 전투 불능`,
    fell: (who: string) => `${who}이(가) 쓰러졌다.`,
    enemySealEscape: '적이 영주를 사용해 도주했다.',
    enemyHoldsOn: (who: string) => `${who}은(는) 물러서지 않는다. 한 번 더 맞으면 쓰러질 것이다.`,
    enemySeal: (purpose: string) => `적이 영주를 사용했다: ${purpose}`,
    enemyWantsFight: '상대는 싸울 생각이다.',
    enemyWantsFlee: '상대가 물러나려 한다.',
    battleEndLabel: '전투 종료',
    drawReason: (n: number) => `${n}국면 소진, 양측 생존`,
  },
  victoryTitle: '우승',
  // 성배 소원 (D-142): 우승하면 성배 앞에서 소원을 적는다
  grail: '성배',
  wishLabel: '소원',
  wishPlaceholder: '소원을 적는다',
  wishSubmit: '소원을 빈다',
  wishCount: (n: number, max: number) => `${n} / ${max}`,
  wishMade: '성배에 빈 소원',
  victoryBody: '성배는 당신의 손에 들어왔다.',
  epiloguePending: '에필로그는 이벤트 로그를 바탕으로 나중에 쓰인다 (AI 에필로그, 후순위).',
  defeatTitle: '패배',
  defeatCause: { killed: '서번트가 쓰러졌다.', escape_failed: '도주에 실패했다.', betrayal: '서번트에게 살해당했다.', refused_escape: '서번트가 도주 명령을 거부하고 쓰러졌다.' } as Record<string, string>,
  // 전쟁 결산 (D-156): 끝나면 모든 진영의 진명·마스터·결과를 공개한다
  warSummary: '전쟁 결산',
  winnerLabel: '성배를 손에 넣은 것은',
  noWinner: '승자 없이 끝났다',
  you: '당신',
  youTag: '나',
  winTag: '우승',
  outcome: (day: string, how: string, by: string | null) => `${day} ${how}${by ? ` ← ${by}` : ''}`,
  elimHow: { killed: '격파', executed: '처치', released: '방면', escape_failed: '도주 실패', betrayal: '배신', refused_escape: '명령 거부 후 격파' } as Record<string, string>,
  backToMain: '메인으로',
  seed: '시드',
  speed: { slow: '느림', normal: '보통', fast: '빠름' } as Record<string, string>,
  auto: '자동',
  history: '기록',
} as const;
